# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: publish-docs
on:
  release:
    types: [published]
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  BUILD_CONFIGURATION: 'Release'
  NUGET_OUTPUT: ${{ github.workspace }}/nuget

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore tools
      run: dotnet tool restore

    - name: Restore dependencies
      run: dotnet restore

    - name: Build software  
      run: dotnet build --configuration ${{env.BUILD_CONFIGURATION}} --no-restore

    - name: Build documentation
      working-directory: docs
      run: dotnet docfx docfx.json
      continue-on-error: false

    - name: Publish documentation
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_site
        force_orphan: true